name: CD

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-now build
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v2.0.0
      with:
        # zeit.co token
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
