name: CD

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm audit fix 
    - run: npm run now-build
    - run: npm i -g now@16.4.4
    - run: now --prod -t ${{ secrets.ZEIT_TOKEN }} -e REACT_APP_FIREBASE_CONFIG=${{secrets.REACT_APP_FIREBASE_CONFIG}} deploy dist
